# -*- coding: utf-8 -*-
"""
Statistical comparison of DEAC against the deep baselines over 12 datasets.

Paired dataset-level tests on mean ARI:
  * Wilcoxon signed-rank: DEAC vs. each deep method (12 paired datasets)
  * Friedman test across all 5 methods + average ranks (Nemenyi CD)

DEAC ARI = paper main-results values; deep methods = mean over 5 seeds.
Output: paper/generated/deep_stats_table.tex + console.
"""
import json
import os

import numpy as np
from scipy.stats import wilcoxon, friedmanchisquare, rankdata, studentized_range

ROOT = os.path.dirname(os.path.abspath(__file__))
DEEP_DIR = os.path.join(ROOT, "results_deep")
OUT_TEX = os.path.join(ROOT, "paper", "generated", "deep_stats_table.tex")

DEAC_ARI = {
    "Wine": 0.802, "Glass": 0.174, "Olivetti": 0.342, "CNAE-9": 0.658,
    "COIL-20": 0.777, "Optdigits": 0.868, "MFeat": 0.937, "Segmentation": 0.465,
    "ISOLET": 0.498, "Satimage": 0.591, "USPS": 0.865, "PenDigits": 0.810,
}
ORDER = list(DEAC_ARI.keys())
DEEP = ["N2D", "DEC", "IDEC", "DCN"]


def main():
    # build matrix [datasets x methods], methods = [DEAC, N2D, DEC, IDEC, DCN]
    deac, deepvals = [], {m: [] for m in DEEP}
    for name in ORDER:
        with open(os.path.join(DEEP_DIR, f"{name}.json"), encoding="utf-8") as f:
            d = json.load(f)
        deac.append(DEAC_ARI[name])
        for m in DEEP:
            deepvals[m].append(d["methods"][m]["ARI_mean"])
    deac = np.array(deac)

    # ---- Wilcoxon: DEAC vs each ----
    print("Wilcoxon signed-rank (DEAC vs method), n=12 datasets:")
    wil = {}
    for m in DEEP:
        x = deac - np.array(deepvals[m])
        try:
            W, p = wilcoxon(deac, deepvals[m])
        except Exception:
            W, p = float("nan"), float("nan")
        wins = int(np.sum(x > 0)); losses = int(np.sum(x < 0))
        wil[m] = (W, p, wins, losses)
        sig = "sig" if p < 0.05 else "n.s."
        print(f"  DEAC vs {m:5s}: W={W:.1f}  p={p:.4f}  ({sig})  win/loss={wins}/{losses}")

    # ---- Friedman + ranks ----
    M = np.column_stack([deac] + [deepvals[m] for m in DEEP])  # 12 x 5
    chi2, pf = friedmanchisquare(*[M[:, j] for j in range(M.shape[1])])
    # average ranks (1 = best, higher ARI = better -> rank descending)
    ranks = np.zeros_like(M)
    for i in range(M.shape[0]):
        ranks[i] = rankdata(-M[i])
    avg_ranks = ranks.mean(0)
    names = ["DEAC"] + DEEP
    print(f"\nFriedman: chi2={chi2:.3f}, p={pf:.5f}")
    print("Average ranks (lower=better):")
    for nm, r in sorted(zip(names, avg_ranks), key=lambda t: t[1]):
        print(f"  {nm:5s}: {r:.2f}")

    # Nemenyi critical difference (alpha=0.05)
    k, N = len(names), M.shape[0]
    q_alpha = studentized_range.ppf(0.95, k, np.inf) / np.sqrt(2)
    CD = q_alpha * np.sqrt(k * (k + 1) / (6.0 * N))
    print(f"Nemenyi CD (alpha=0.05) = {CD:.3f}")

    # ---- LaTeX ----
    L = [r"% Auto-generated by build_deep_stats.py",
         r"\begin{table}[htbp]", r"\centering",
         r"\caption{Statistical comparison vs.\ deep methods over 12 datasets. "
         r"Wilcoxon signed-rank (two-tailed) and Friedman average ranks.}",
         r"\label{tab:deepstats}", r"\footnotesize",
         r"\begin{tabular}{lcccc}", r"\toprule",
         r"Comparison & $W$ & $p$-value & Win/Loss & Avg.\ rank \\",
         r"\midrule"]
    rank_map = dict(zip(names, avg_ranks))
    L.append(f"\\textbf{{DEAC}} & --- & --- & --- & {rank_map['DEAC']:.2f} \\\\")
    for m in DEEP:
        W, p, wins, losses = wil[m]
        star = r"$^{*}$" if p < 0.05 else ""
        L.append(f"DEAC vs {m} & {W:.0f} & {p:.4f}{star} & {wins}/{losses} & {rank_map[m]:.2f} \\\\")
    L.append(r"\midrule")
    L.append(f"\\multicolumn{{5}}{{l}}{{\\footnotesize Friedman $\\chi^2(4){{=}}{chi2:.2f}$, "
             f"$p{{=}}{pf:.4f}$; Nemenyi CD${{=}}{CD:.2f}$. $^{{*}}p<0.05$.}} \\\\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"\nWrote: {OUT_TEX}")


if __name__ == "__main__":
    main()
