# -*- coding: utf-8 -*-
"""
Aggregate deep-baseline results (results_deep/*.json) and emit a LaTeX
comparison table: DEAC vs. modern deep methods (N2D, DEC, IDEC, DCN).

DEAC per-dataset ARI values are taken from the paper's main results table
(Table tab:main_results, DEAC column). Deep methods use the true cluster
count (oracle C); DEAC discovers C automatically.

Output: paper/generated/deep_comparison_table.tex  (+ console summary)
"""
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.abspath(__file__))
DEEP_DIR = os.path.join(ROOT, "results_deep")
OUT_TEX = os.path.join(ROOT, "paper", "generated", "deep_comparison_table.tex")

# DEAC ARI from the paper (Table tab:main_results, DEAC column)
DEAC_ARI = {
    "Wine": 0.802, "Glass": 0.174, "Olivetti": 0.342, "CNAE-9": 0.658,
    "COIL-20": 0.777, "Optdigits": 0.868, "MFeat": 0.937, "Segmentation": 0.465,
    "ISOLET": 0.498, "Satimage": 0.591, "USPS": 0.865, "PenDigits": 0.810,
}
ORDER = list(DEAC_ARI.keys())
DEEP = ["N2D", "DEC", "IDEC", "DCN"]


def load_all():
    data = {}
    for name in ORDER:
        p = os.path.join(DEEP_DIR, f"{name}.json")
        if os.path.exists(p):
            with open(p, encoding="utf-8") as f:
                data[name] = json.load(f)
    return data


def fmt(mean, std, bold=False):
    s = f"{mean:.3f}\\,\\pm\\,{std:.3f}"
    return f"$\\mathbf{{{s}}}$" if bold else f"${s}$"


def main():
    data = load_all()
    done = [n for n in ORDER if n in data]
    print(f"Datasets available: {len(done)}/12 -> {done}\n")

    rows = []
    deac_vals, deep_means = [], {m: [] for m in DEEP}
    deac_wins = 0
    n_complete = 0

    for name in ORDER:
        if name not in data:
            continue
        n_complete += 1
        d = DEAC_ARI[name]
        deac_vals.append(d)
        method_means = {"DEAC": d}
        for m in DEEP:
            mm = data[name]["methods"][m]["ARI_mean"]
            method_means[m] = mm
            deep_means[m].append(mm)
        best = max(method_means.values())
        if d >= best - 1e-9:
            deac_wins += 1
        rows.append((name, data[name], method_means, best))

    # ---- console ----
    hdr = f"{'Dataset':<13}{'DEAC':>9}" + "".join(f"{m:>9}" for m in DEEP) + "   winner"
    print(hdr)
    print("-" * len(hdr))
    for name, d, mm, best in rows:
        winner = max(mm, key=mm.get)
        line = f"{name:<13}{mm['DEAC']:>9.3f}" + "".join(f"{mm[m]:>9.3f}" for m in DEEP)
        print(line + f"   {winner}")
    print("-" * len(hdr))
    mrow = f"{'MEAN':<13}{np.mean(deac_vals):>9.3f}" + "".join(
        f"{np.mean(deep_means[m]):>9.3f}" for m in DEEP)
    print(mrow)
    print(f"\nDEAC best-or-tied on {deac_wins}/{n_complete} datasets (vs deep methods).")

    # ---- LaTeX ----
    L = []
    L.append(r"% Auto-generated by build_deep_comparison.py")
    L.append(r"\begin{table*}[!t]")
    L.append(r"\centering")
    L.append(r"\caption{ARI vs.\ modern deep-clustering methods (mean$\pm$std over "
              r"5 seeds). Deep methods receive the true cluster count (oracle $C$); "
              r"DEAC discovers $C$. Bold = best per row.}")
    L.append(r"\label{tab:deep}")
    L.append(r"\footnotesize")
    L.append(r"\setlength{\tabcolsep}{3pt}")
    L.append(r"\begin{tabular}{lccccc}")
    L.append(r"\toprule")
    L.append(r"Dataset & \textbf{DEAC} & N2D & DEC & IDEC & DCN \\")
    L.append(r"\midrule")
    for name, d, mm, best in rows:
        cells = []
        # DEAC (no std — single reported value from paper)
        cells.append(f"$\\mathbf{{{mm['DEAC']:.3f}}}$" if mm['DEAC'] >= best - 1e-9
                     else f"{mm['DEAC']:.3f}")
        for m in DEEP:
            s = data[name]["methods"][m]
            isbest = s["ARI_mean"] >= best - 1e-9
            cells.append(fmt(s["ARI_mean"], s["ARI_std"], isbest))
        L.append(f"{name} & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    mean_cells = [f"{np.mean(deac_vals):.3f}"]
    for m in DEEP:
        mean_cells.append(f"{np.mean(deep_means[m]):.3f}")
    # bold the best mean
    allmeans = [np.mean(deac_vals)] + [np.mean(deep_means[m]) for m in DEEP]
    bi = int(np.argmax(allmeans))
    mean_cells[bi] = f"$\\mathbf{{{allmeans[bi]:.3f}}}$"
    L.append(r"\textbf{Mean} & " + " & ".join(mean_cells) + r" \\")
    # wins row (best-or-tied per dataset)
    wins = {"DEAC": 0, "N2D": 0, "DEC": 0, "IDEC": 0, "DCN": 0}
    for name, d, mm, best in rows:
        for k, v in mm.items():
            if v >= best - 1e-9:
                wins[k] += 1
    nd = len(rows)
    win_cells = [f"{wins['DEAC']}/{nd}"] + [f"{wins[m]}/{nd}" for m in DEEP]
    bw = int(np.argmax([wins['DEAC']] + [wins[m] for m in DEEP]))
    vals = [wins['DEAC']] + [wins[m] for m in DEEP]
    win_cells[bw] = f"$\\mathbf{{{vals[bw]}/{nd}}}$"
    L.append(r"\textbf{Wins} & " + " & ".join(win_cells) + r" \\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table*}")

    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"\nWrote: {OUT_TEX}")


if __name__ == "__main__":
    main()
