# -*- coding: utf-8 -*-
"""
Build the FAIR classical-baseline comparison table (auto-C) + statistics.

Reads results_autoc/*.json (classical baselines with silhouette-selected C)
and compares against DEAC (paper main-results ARI). Emits:
  paper/generated/autoc_comparison_table.tex   (per-dataset ARI + Wins)
Console: Wilcoxon (DEAC vs each) + Friedman + ranks.
"""
import json
import os

import numpy as np
from scipy.stats import wilcoxon, friedmanchisquare, rankdata

ROOT = os.path.dirname(os.path.abspath(__file__))
AUTOC_DIR = os.path.join(ROOT, "results_autoc")
OUT_TEX = os.path.join(ROOT, "paper", "generated", "autoc_comparison_table.tex")

DEAC_ARI = {
    "Wine": 0.802, "Glass": 0.174, "Olivetti": 0.342, "CNAE-9": 0.658,
    "COIL-20": 0.777, "Optdigits": 0.868, "MFeat": 0.937, "Segmentation": 0.465,
    "ISOLET": 0.498, "Satimage": 0.591, "USPS": 0.865, "PenDigits": 0.810,
}
ORDER = list(DEAC_ARI.keys())
CLA = ["KMeans", "Spectral", "Agglomerative", "GMM", "HDBSCAN"]
SHORT = {"KMeans": "KM", "Spectral": "Spec", "Agglomerative": "Agg",
         "GMM": "GMM", "HDBSCAN": "HDB"}


def main():
    data = {}
    for name in ORDER:
        p = os.path.join(AUTOC_DIR, f"{name}.json")
        if os.path.exists(p):
            with open(p, encoding="utf-8") as f:
                data[name] = json.load(f)
    done = [n for n in ORDER if n in data]
    print(f"Available: {len(done)}/12 -> {done}\n")
    if not done:
        return

    deac = np.array([DEAC_ARI[n] for n in done])
    clav = {m: np.array([data[n]["methods"][m]["ARI_mean"] for n in done]) for m in CLA}

    # console
    hdr = f"{'Dataset':<13}{'DEAC':>8}" + "".join(f"{SHORT[m]:>8}" for m in CLA) + f"{'C*sel':>7}"
    print(hdr); print("-" * len(hdr))
    for i, n in enumerate(done):
        line = f"{n:<13}{deac[i]:>8.3f}" + "".join(f"{clav[m][i]:>8.3f}" for m in CLA)
        print(line + f"{data[n]['C_selected_mean']:>7.1f}")
    print("-" * len(hdr))
    print(f"{'MEAN':<13}{deac.mean():>8.3f}" + "".join(f"{clav[m].mean():>8.3f}" for m in CLA))

    # stats
    print("\nWilcoxon (DEAC vs method), n=%d:" % len(done))
    for m in CLA:
        try:
            W, p = wilcoxon(deac, clav[m])
        except Exception:
            W, p = float("nan"), float("nan")
        w = int(np.sum(deac > clav[m])); l = int(np.sum(deac < clav[m]))
        print(f"  vs {m:14s}: W={W:.1f} p={p:.4f} win/loss={w}/{l} {'sig' if p<0.05 else 'n.s.'}")
    M = np.column_stack([deac] + [clav[m] for m in CLA])
    chi2, pf = friedmanchisquare(*[M[:, j] for j in range(M.shape[1])])
    ranks = np.vstack([rankdata(-M[i]) for i in range(M.shape[0])]).mean(0)
    names = ["DEAC"] + CLA
    print(f"\nFriedman chi2={chi2:.2f} p={pf:.5f}")
    for nm, r in sorted(zip(names, ranks), key=lambda t: t[1]):
        print(f"  {nm:14s}: {r:.2f}")

    # wins per method (best-or-tied)
    wins = {nm: 0 for nm in names}
    for i in range(len(done)):
        row = {nm: M[i, j] for j, nm in enumerate(names)}
        best = max(row.values())
        for nm, v in row.items():
            if v >= best - 1e-9:
                wins[nm] += 1

    # LaTeX
    L = [r"% Auto-generated by build_autoc_comparison.py",
         r"\begin{table}[!t]", r"\centering",
         r"\caption{ARI vs.\ classical methods with \emph{automatic} cluster-count "
         r"selection (each baseline's $C$ chosen by silhouette analysis, not given "
         r"DEAC's $C^*$). Mean over 5 seeds; bold = best per row. DEAC is the "
         r"oracle upper bound (cf.\ Table~\ref{tab:gate}).}",
         r"\label{tab:benchmarks}", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{lcccccc}", r"\toprule",
         r"Dataset & \textbf{DEAC} & KM & Spec & Agg & GMM & HDB \\", r"\midrule"]
    nd = len(done)
    for i, n in enumerate(done):
        row = {"DEAC": deac[i], **{m: clav[m][i] for m in CLA}}
        best = max(row.values())
        cells = [f"$\\mathbf{{{deac[i]:.3f}}}$" if deac[i] >= best - 1e-9 else f"{deac[i]:.3f}"]
        for m in CLA:
            v = clav[m][i]
            cells.append(f"$\\mathbf{{{v:.3f}}}$" if v >= best - 1e-9 else f"{v:.3f}")
        L.append(f"{n} & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    means = [deac.mean()] + [clav[m].mean() for m in CLA]
    bi = int(np.argmax(means))
    mc = [f"{v:.3f}" for v in means]
    mc[bi] = f"$\\mathbf{{{means[bi]:.3f}}}$"
    L.append(r"\textbf{Mean} & " + " & ".join(mc) + r" \\")
    wv = [wins["DEAC"]] + [wins[m] for m in CLA]
    bwi = int(np.argmax(wv))
    wc = [f"{x}/{nd}" for x in wv]
    wc[bwi] = f"$\\mathbf{{{wv[bwi]}/{nd}}}$"
    L.append(r"\textbf{Wins} & " + " & ".join(wc) + r" \\")
    L.append(r"\bottomrule"); L.append(r"\end{tabular}"); L.append(r"\end{table}")
    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"\nWins: {wins}\nWrote: {OUT_TEX}")


if __name__ == "__main__":
    main()
