# -*- coding: utf-8 -*-
"""
Valid significance testing: Wilcoxon signed-rank of DEAC vs. each INDEPENDENT
competitor (5 classical auto-C + 4 deep), with Holm-Bonferroni correction.

Removes the invalid DEAC-vs-Baseline / DEAC-vs-AMR-DE tests (DEAC = max of its
own engines, so those differences are non-negative by construction).

Emits paper/generated/stats_table.tex and prints the corrected results.
"""
import json, os, glob
import numpy as np
from scipy.stats import wilcoxon

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "paper", "generated", "stats_table.tex")
ORDER = ["Wine", "Glass", "Olivetti", "CNAE-9", "COIL-20", "Optdigits",
         "MFeat", "Segmentation", "ISOLET", "Satimage", "USPS", "PenDigits"]
DEAC = {"Wine": 0.802, "Glass": 0.174, "Olivetti": 0.342, "CNAE-9": 0.658,
        "COIL-20": 0.777, "Optdigits": 0.868, "MFeat": 0.937, "Segmentation": 0.465,
        "ISOLET": 0.498, "Satimage": 0.591, "USPS": 0.865, "PenDigits": 0.810}

def load(dirn):
    D = {}
    for f in glob.glob(os.path.join(ROOT, dirn, "*.json")):
        d = json.load(open(f));
        if "methods" in d: D[d["name"]] = d["methods"]
    return D

autoc = load("results_autoc")
deep = load("results_deep")
deac = np.array([DEAC[n] for n in ORDER])

comps = []  # (label, group, vector)
for m in ["KMeans", "Spectral", "Agglomerative", "GMM", "HDBSCAN"]:
    comps.append((m, "classical", np.array([autoc[n][m]["ARI_mean"] for n in ORDER])))
for m in ["N2D", "DEC", "IDEC", "DCN"]:
    comps.append((m, "deep", np.array([deep[n][m]["ARI_mean"] for n in ORDER])))

# raw Wilcoxon
raw = []
for label, grp, v in comps:
    W, p = wilcoxon(deac, v)
    win = int(np.sum(deac > v)); loss = int(np.sum(deac < v))
    raw.append({"label": label, "grp": grp, "W": float(W), "p": float(p),
                "win": win, "loss": loss})

# Holm-Bonferroni across the whole family
m = len(raw)
order_idx = sorted(range(m), key=lambda i: raw[i]["p"])
cummax = 0.0
for rank, i in enumerate(order_idx):
    adj = min(1.0, (m - rank) * raw[i]["p"])
    cummax = max(cummax, adj)
    raw[i]["p_holm"] = cummax
    raw[i]["sig"] = cummax < 0.05

print(f"Holm-Bonferroni over {m} independent comparisons (alpha=0.05):")
for r in raw:
    print(f"  DEAC vs {r['label']:14s} p={r['p']:.4f}  Holm={r['p_holm']:.4f}  "
          f"{'SIG' if r['sig'] else 'n.s.'}  ({r['win']}/{r['loss']})")

# LaTeX
L = [r"% Auto-generated by build_stats_holm.py",
     r"\begin{table}[htbp]", r"\centering",
     r"\caption{Wilcoxon signed-rank tests (two-tailed) of DEAC vs.\ each "
     r"\emph{independent} competitor over 12 datasets, with Holm--Bonferroni "
     r"correction across the family of nine tests. Baseline and AMR-DE are "
     r"omitted, as DEAC is their per-dataset maximum. DEAC here is the oracle "
     r"upper bound (\S\ref{sec:disc}).}",
     r"\label{tab:stats}", r"\footnotesize", r"\setlength{\tabcolsep}{4pt}",
     r"\begin{tabular}{llcccc}", r"\toprule",
     r"Comparison & Type & Win/Loss & $p$ & $p_{\text{Holm}}$ & Sig. \\", r"\midrule"]
for grp in ["classical", "deep"]:
    for r in raw:
        if r["grp"] != grp: continue
        sig = r"$\checkmark$" if r["sig"] else r"$\times$"
        L.append(f"DEAC vs {r['label']} & {grp} & {r['win']}/{r['loss']} & "
                 f"{r['p']:.4f} & {r['p_holm']:.3f} & {sig} \\\\")
    L.append(r"\midrule")
L[-1] = r"\bottomrule"
L += [r"\end{tabular}", r"\end{table}"]
open(OUT, "w", encoding="utf-8").write("\n".join(L))
nsig = sum(r["sig"] for r in raw)
print(f"\n{nsig}/{m} significant after Holm. Wrote {OUT}")
