# -*- coding: utf-8 -*-
"""Emit the deployable-gate vs. oracle-upper-bound table from results_gate/."""
import json, os, glob
import numpy as np

ROOT = os.path.dirname(os.path.abspath(__file__))
GDIR = os.path.join(ROOT, "results_gate")
OUT = os.path.join(ROOT, "paper", "generated", "gate_oracle_table.tex")
ORDER = ["Wine", "Glass", "Olivetti", "CNAE-9", "COIL-20", "Optdigits",
         "MFeat", "Segmentation", "ISOLET", "Satimage", "USPS", "PenDigits"]
SHORT = {"Baseline": "Base", "AMR-DE": "AMR-DE", "EMR-CGC": "EMR"}

D = {json.load(open(f))["name"]: json.load(open(f)) for f in glob.glob(os.path.join(GDIR, "*.json"))}

g = [D[n]["gate_ari"] for n in ORDER]
o = [D[n]["oracle_ari"] for n in ORDER]
b = [D[n]["aris"]["Baseline"] for n in ORDER]
agree = sum(D[n]["gate_pick"] == D[n]["oracle_pick"] for n in ORDER)
mg, mo, mb = np.mean(g), np.mean(o), np.mean(b)
recov = 100 * (mg - mb) / (mo - mb)

L = [r"% Auto-generated by build_gate_oracle.py",
     r"\begin{table}[!t]", r"\centering",
     r"\caption{Deployable QualityGate (selects among the three engines by "
     r"internal metrics, \emph{no labels}) vs.\ the oracle upper bound "
     r"(best-ARI engine per dataset). Full data, single seed with our exact "
     r"pipeline, so absolute ARIs differ marginally from the five-seed main "
     r"tables. $\Delta$ is oracle$-$gate.}",
     r"\label{tab:gate}", r"\footnotesize", r"\setlength{\tabcolsep}{4pt}",
     r"\begin{tabular}{lccc c}", r"\toprule",
     r"Dataset & Gate pick & Gate ARI & Oracle ARI & $\Delta$ \\", r"\midrule"]
for n in ORDER:
    d = D[n]
    match = d["gate_pick"] == d["oracle_pick"]
    gp = SHORT.get(d["gate_pick"], d["gate_pick"])
    ga = f"$\\mathbf{{{d['gate_ari']:.3f}}}$" if match else f"{d['gate_ari']:.3f}"
    L.append(f"{n} & {gp} & {ga} & {d['oracle_ari']:.3f} & "
             f"{d['oracle_ari']-d['gate_ari']:+.3f} \\\\")
L.append(r"\midrule")
L.append(f"\\textbf{{Mean}} & --- & \\textbf{{{mg:.3f}}} & {mo:.3f} & {mo-mg:+.3f} \\\\")
L.append(r"\bottomrule")
L.append(r"\end{tabular}")
L.append(r"\end{table}")
open(OUT, "w", encoding="utf-8").write("\n".join(L))
print(f"gate={mg:.3f} oracle={mo:.3f} baseline={mb:.3f} recover={recov:.0f}% agree={agree}/12")
print("Wrote", OUT)
